www/modules/merchant/controllers/StaffController.php
<?php

namespace www\modules\merchant\controllers;

use common\components\DataHelper;
use common\components\GlobalUrlService;
use common\models\merchant\MerchantStaff;
use common\services\Constants;
use common\services\MerchantService;
use www\modules\merchant\controllers\common\AuthController;


class StaffController extends AuthController{

    public function actionIndex(){
        $p = intval( $this->get("p",1) );
        $query = MerchantStaff::find();
        $total_count = $query->count();
        $offset = ($p - 1) * $this->page_size;
        $list = $query->offset($offset)
            ->limit( $this->page_size )
            ->asArray()->all();

        $pages = DataHelper::ipagination([
            "total_count" => $total_count,
            "page_size" => $this->page_size,
            "page" => $p,
            "display" => 10
        ]);

        return $this->render('index',[
            "list" => $list,
            "pages" => $pages
        ]);
    }

    public function actionSet(  ){


        if( \Yii::$app->request->isGet ){
            $id = intval( $this->get("id",0 ) );
            $staff_info = [];
            if( $id ){
                $staff_info = MerchantStaff::findOne([ 'id' => $id ]);
            }

            $info = [];
            if( $staff_info ){
                $info['id'] = $staff_info['id'];
                $info['avatar'] = $staff_info['avatar'];
                $info['nickname'] = $staff_info['nickname'];
                $info['login_name'] = $staff_info['login_name'];
                $info['login_pwd'] = Constants::$default_login_pwd;
            }
            return $this->render("set",[ "info" => $info ]);
        }
        $id = $this->post("id",0);
        $avatar = Constants::$default_kf_avatar;
        $nickname = trim($this->post('nickname',''));
        $login_name = trim($this->post('login_name',''));
        $login_pwd = $this->post('login_pwd','');
        if( mb_strlen($nickname,'utf-8') < 1 ){
            return $this->renderJSON([],"请输入符合规范的昵称~~",-1);
        }

        if( mb_strlen( $login_name,'utf-8') < 4 || mb_strlen($login_name,'utf-8') > 11){
            return $this->renderJSON([],"请输入符合规范的登录用户名，登录名称介于4 - 11 个字符~~",-1);
        }

        if( mb_strlen( $login_pwd,'utf-8') < 6 ){
            return $this->renderJSON([],"请输入符合规范的密码，密码不能少于6位~",-1);
        }

        $same_login_name_staff = MerchantStaff::find()
            ->where([ 'login_name' => $login_name ])
            ->andWhere( ['!=','id',$id] )->one();

        if( $same_login_name_staff ){
            return $this->renderJSON([],"登录账号已被占用，请换一个试试哦~~",-1);
        }

        $staff_info = MerchantStaff::findOne([ 'id' => $id ]);

        if( $staff_info ){
            $model_staff = $staff_info;
        }else{
            $model_staff = new MerchantStaff();
            $model_staff->setSalt();
            $model_staff->sn = MerchantService::getStaffUniqueSn( $login_name );
        }
        $model_staff->avatar = $avatar;
        $model_staff->nickname = $nickname;
        if( $model_staff->login_name != $login_name ){
            $model_staff->login_name = $login_name;
        }

        if( $login_pwd != Constants::$default_login_pwd  && $model_staff->getSaltPassword( $login_pwd ) != $model_staff->login_pwd ){
            $model_staff->setPassword( $login_pwd );
        }

        $model_staff->save( 0 );
        return $this->renderJSON();
    }
}

www/modules/merchant/views/staff/index.php
<?php
use \common\components\GlobalUrlService;
use \common\components\DataHelper;
use \common\services\Constants;
?>
<div class="row">
    <div class="row-in">
        <div class="columns-24">
            <?php echo \Yii::$app->view->renderFile("@www/modules/merchant/views/staff/tab.php", ['current' => 'index']); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="row-in">
        <div class="title-3a">
            <div class="columns-16">
                <p>搜索结果：共<?=$pages['total_count'];?>人</p>
            </div>
            <div class="columns-8 right">
                <a href="<?=GlobalUrlService::buildMerchantUrl("/staff/set");?>" class="btn-small style-3 mg-r10">+添加客服</a>
            </div>
        </div>
        <div class="columns-24">
            <table class="table-1">
                <thead>
                <tr>
                    <td width="8%">客服标识</td>
                    <td>客服昵称</td>
                    <td width="8%">客服头像</td>
                    <td width="8%">客服状态</td>
                    <td width="8%">在线状态</td>
                    <td width="20%">操作</td>
                </tr>
                </thead>
                <tbody>
                <?php if( $list ):?>
                    <?php foreach( $list as $_item ):?>
                        <tr>
                            <td><?=DataHelper::encode( $_item['sn'] );?></td>
                            <td><?=DataHelper::encode( $_item['nickname'] );?></td>
                            <td>
                                <div class="avatar-1">
                                    <img src="<?=GlobalUrlService::buildWwwStaticUrl( "/images/{$_item['avatar']}" );?>"/>
                                </div>

                            </td>
                            <td class="<?=($_item['status'])?"color-success":"color-danger";?>">
                                <?=Constants::$login_status_map[ $_item['status'] ];?>
                            </td>
                            <td class="<?=(!$_item['online_status'])?"color-success":"color-danger";?>">
                                <?=Constants::$online_status_map[ $_item['online_status'] ];?>
                            </td>
                            <td>
                                <a class="color-theme edit" href="<?=GlobalUrlService::buildMerchantUrl("/staff/set",[ "id" => $_item['id'] ]);?>">
                                    <i class="fa fa-pencil" aria-hidden="true"></i>编辑
                                </a>
                            </td>
                        </tr>
                    <?php endforeach;?>
                <?php else:?>
                    <tr>
                        <td colspan="6" class="centered">暂无信息</td>
                    </tr>
                <?php endif;?>
                </tbody>
            </table>
        </div>
        <div class="columns-24 text-right">
            <?php echo \Yii::$app->view->renderFile("@www/modules/merchant/views/common/pagination.php",[
                'pages' => $pages,
                'url' => '/staff/index',
                'search_conditions' => [],
                'current_page_count' => count($list)
            ]);?>
        </div>
    </div>
</div>

www/modules/merchant/views/staff/set.php
<?php

use \common\components\GlobalUrlService;
use \common\components\StaticService;


StaticService::includeAppJsStatic("/static/js/merchant/staff/set.js",\www\assets\MerchantAsset::className() );
?>
<div class="row">
    <div class="row-in">
        <div class="columns-24">
            <?php echo \Yii::$app->view->renderFile("@www/modules/merchant/views/staff/tab.php", ['current' => 'index']); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="row-in wrap_staff_set">
        <div class="columns-12 offset-6 mg-t30">
            <div class="row">
                <div class="row-in">
                    <div class="columns-6">
                        <label class="label-name right inline"><i class="mark">*</i>昵称</label>
                    </div>
                    <div class="columns-18">
                        <div class="input-wrap">
                            <input type="text" name="nickname" class="input-1" value="<?=isset( $info['nickname'] )?$info['nickname']:'';?>" placeholder="请输入客服昵称">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="row-in">
                    <div class="columns-6">
                        <label class="label-name right inline"><i class="mark">*</i>登录用户名</label>
                    </div>
                    <div class="columns-18">
                        <div class="input-wrap">
                            <input type="text" name="login_name" class="input-1" value="<?=isset( $info['login_name'] )?$info['login_name']:'';?>" placeholder="请输入登录用户名，建议使用手机号码~~">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="row-in">
                    <div class="columns-6">
                        <label class="label-name right inline"><i class="mark">*</i>登录密码</label>
                    </div>
                    <div class="columns-18">
                        <div class="input-wrap">
                            <input type="text" name="login_pwd" class="input-1" placeholder="请输入登录密码~~" value="<?=isset( $info['login_pwd'] )?$info['login_pwd']:'';?>">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="row-in">
                    <p class="columns-6 offset-6">
                        <input type="hidden" name="id" value="<?=isset( $info['id'] )?$info['id']:0;?>">
                        <input type="button" value="保存" class="btn-small save">
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

www/modules/merchant/views/staff/tab.php
<?php
use \common\components\GlobalUrlService;

$mapping = [
    "index" =>  [
        "title" => "客服列表",
        "url" => GlobalUrlService::buildMerchantUrl("/staff/index")
    ]
];
?>

<ul class="tab_title style_1">
    <?php foreach( $mapping as $_key => $_item ):?>
        <li <?php if($current == $_key ):?> class="current" <?php endif;?>>
            <a href="<?=$_item['url'];?>"><?=$_item["title"];?></a>
        </li>
    <?php endforeach;?>
</ul>