www/modules/merchant/controllers/ChatController.php
<?php

namespace www\modules\merchant\controllers;

use common\components\DataHelper;
use common\components\GlobalUrlService;
use common\models\ChatHistory;
use common\models\guest\GuestMessage;
use www\modules\merchant\controllers\common\AuthController;

class ChatController extends AuthController{

    public function actionLog(){

        $p = intval( $this->get("p",1) );
        $query = ChatHistory::find();
        $total_count = $query->count();
        $offset = ($p - 1) * $this->page_size;
        $list = $query->offset($offset)->orderBy([ 'id' => SORT_DESC ])
            ->limit( $this->page_size )->all();

        $pages = DataHelper::ipagination([
            "total_count" => $total_count,
            "page_size" => $this->page_size,
            "page" => $p,
            "display" => 10
        ]);

        return $this->render('log',[
            "list" => $list,
            "pages" => $pages
        ]);
    }
}

www/modules/merchant/controllers/HelpController.php
<?php

namespace www\modules\merchant\controllers;

use common\components\GlobalUrlService;
use www\modules\merchant\controllers\common\AuthController;

/**
 * Default controller for the `merchant` module
 */
class HelpController extends AuthController{

    public function actionIndex(){
        $merchant_sn = $this->current_user['sn'];
        $url = GlobalUrlService::buildWwwUrl("/code/index");
        $url_cs = GlobalUrlService::buildCsUrl("/default/index" );
        $url = str_replace("https:","",$url);
        $url = str_replace("http:","",$url);
        return $this->render('index',[ "url" => $url,"url_cs" => $url_cs ]);
    }

    public function actionCs(){
        $url_cs = GlobalUrlService::buildCsUrl("/default/index" );
        return $this->redirect( $url_cs );
    }
}

www/modules/merchant/controllers/StatController.php
<?php

namespace www\modules\merchant\controllers;

use common\components\DataHelper;
use common\components\GlobalUrlService;
use common\models\ChatHistory;
use common\models\guest\GuestMessage;
use common\models\GuestTrace;
use common\models\stat\StatDailyAccessSource;
use common\models\stat\StatDailyBrowser;
use common\models\stat\StatDailyOs;
use common\models\stat\StatDailyUuid;
use common\services\ip\IPService;
use www\modules\merchant\controllers\common\AuthController;


class StatController extends AuthController{

    public function actionTrace(){
        $p = intval( $this->get("p",1) );
        $date_from = $this->get("date_from",date("Y-m-01") );
        $date_to = $this->get("date_to",date("Y-m-d") );

        $source = trim( $this->get("source","") );
        $uuid = trim( $this->get("uuid",""));
        $client_os = trim( $this->get("client_os",""));
        $client_browser = trim( $this->get("client_browser",""));

        $query = GuestTrace::find();
        if( $date_from ){
            $query->andWhere([ '>=','created_time',date("Y-m-d 00:00:00",strtotime( $date_from ) ) ]);
        }
        if( $date_from ){
            $query->andWhere([ '<=','created_time',date("Y-m-d 23:59:59",strtotime( $date_to ) ) ]);
        }

        if( $source ){
            $query->andWhere([ 'source' => $source ]);
        }

        if( $uuid ){
            $query->andWhere([ 'f_code' => $uuid ]);
        }

        if( $client_os ){
            $query->andWhere([ 'client_os' => $client_os ]);
        }

        if( $client_browser ){
            $query->andWhere([ 'client_browser' => $client_browser ]);
        }

        $total_count = $query->count();
        $offset = ($p - 1) * $this->page_size;
        $list = $query->offset($offset)->orderBy([ 'id' => SORT_DESC ])
            ->limit( $this->page_size )->asArray()->all();

        $pages = DataHelper::ipagination([
            "total_count" => $total_count,
            "page_size" => $this->page_size,
            "page" => $p,
            "display" => 10
        ]);

        $data = [];
        if( $list ){
            foreach( $list as $_item){
                $_item[ 'ip_desc' ] = implode(" ",IPService::find($_item['ip']) );
                $data[] = $_item;
            }
        }

        $search_conditions = [
            'date_from' => $date_from,
            'date_to' => $date_to,
            'source' => $source,
            'uuid' => $uuid,
            'client_os' => $client_os,
            'client_browser' => $client_browser
        ];

        return $this->render('trace',[
            "list" => $data,
            "pages" => $pages,
            'search_conditions' => $search_conditions
        ]);
    }

    public function actionUuid(){
        $date_from = $this->get("date_from",date("Y-m-d") );
        $date_to = $this->get("date_to",date("Y-m-d") );

        $p = intval( $this->get("p",1) );
        if(!$p){
            $p = 1;
        }


        $query = StatDailyUuid::find();
        if( $date_from ){
            $query->andWhere([ '>=','date',date("Y-m-d",strtotime( $date_from ) ) ]);
        }
        if( $date_from ){
            $query->andWhere([ '<=','date',date("Y-m-d",strtotime( $date_to ) ) ]);
        }

        $total_count = $query->count();
        $offset = ($p - 1) * $this->page_size;
        $list = $query->orderBy("id desc")->offset($offset)->limit( $this->page_size )->all();

        $pages = DataHelper::ipagination([
            "total_count" => $total_count,
            "page_size" => $this->page_size,
            "page" => $p,
            "display" => 10
        ]);

        $search_conditions = [
            'date_from' => $date_from,
            'date_to' => $date_to,
        ];
        return $this->render("uuid",[
            "data" => $list,
            "pages" => $pages,
            'search_conditions' => $search_conditions
        ]);
    }

    public function actionSource(){
        $date_from = $this->get("date_from",date("Y-m-d") );
        $date_to = $this->get("date_to",date("Y-m-d") );

        $p = intval( $this->get("p",1) );
        if(!$p){
            $p = 1;
        }


        $query = StatDailyAccessSource::find();
        if( $date_from ){
            $query->andWhere([ '>=','date',date("Y-m-d",strtotime( $date_from ) ) ]);
        }
        if( $date_from ){
            $query->andWhere([ '<=','date',date("Y-m-d",strtotime( $date_to ) ) ]);
        }

        $total_count = $query->count();
        $offset = ($p - 1) * $this->page_size;
        $list = $query->orderBy("id desc")->offset($offset)->limit( $this->page_size )->all();

        $pages = DataHelper::ipagination([
            "total_count" => $total_count,
            "page_size" => $this->page_size,
            "page" => $p,
            "display" => 10
        ]);


        $search_conditions = [
            'date_from' => $date_from,
            'date_to' => $date_to,
        ];
        return $this->render("source",[
            "data" => $list,
            "pages" => $pages,
            'search_conditions' => $search_conditions
        ]);
    }

    public function actionOs(){
        $date_from = $this->get("date_from",date("Y-m-d") );
        $date_to = $this->get("date_to",date("Y-m-d") );

        $p = intval( $this->get("p",1) );
        if(!$p){
            $p = 1;
        }


        $query = StatDailyOs::find();
        if( $date_from ){
            $query->andWhere([ '>=','date',date("Y-m-d",strtotime( $date_from ) ) ]);
        }
        if( $date_from ){
            $query->andWhere([ '<=','date',date("Y-m-d",strtotime( $date_to ) ) ]);
        }

        $total_count = $query->count();
        $offset = ($p - 1) * $this->page_size;
        $list = $query->orderBy([ 'id' => SORT_DESC ])->offset($offset)->limit( $this->page_size )->all();

        $pages = DataHelper::ipagination([
            "total_count" => $total_count,
            "page_size" => $this->page_size,
            "page" => $p,
            "display" => 10
        ]);


        $search_conditions = [
            'date_from' => $date_from,
            'date_to' => $date_to,
        ];
        return $this->render("os",[
            "data" => $list,
            "pages" => $pages,
            'search_conditions' => $search_conditions
        ]);
    }

    public function actionBrowser(){
        $date_from = $this->get("date_from",date("Y-m-d") );
        $date_to = $this->get("date_to",date("Y-m-d") );

        $p = intval( $this->get("p",1) );
        if(!$p){
            $p = 1;
        }


        $query = StatDailyBrowser::find();
        if( $date_from ){
            $query->andWhere([ '>=','date',date("Y-m-d",strtotime( $date_from ) ) ]);
        }
        if( $date_from ){
            $query->andWhere([ '<=','date',date("Y-m-d",strtotime( $date_to ) ) ]);
        }

        $total_count = $query->count();
        $offset = ($p - 1) * $this->page_size;
        $list = $query->orderBy([ 'id' => SORT_DESC ])->offset($offset)->limit( $this->page_size )->all();

        $pages = DataHelper::ipagination([
            "total_count" => $total_count,
            "page_size" => $this->page_size,
            "page" => $p,
            "display" => 10
        ]);


        $search_conditions = [
            'date_from' => $date_from,
            'date_to' => $date_to,
        ];
        return $this->render("browser",[
            "data" => $list,
            "pages" => $pages,
            'search_conditions' => $search_conditions
        ]);
    }
}

www/modules/merchant/controllers/UserController.php
<?php

namespace www\modules\merchant\controllers;
use common\components\GlobalUrlService;
use www\modules\merchant\controllers\common\AuthController;

class UserController extends AuthController{

    public function actionLogout(){
        $this->removeAuthToken( $this->auth_merchant_cookie );
        return $this->redirect( GlobalUrlService::buildWwwUrl("/") );
    }
}

www/modules/merchant/views/layouts/main.php
<?php
use www\assets\MerchantAsset;
use \common\components\GlobalUrlService;
MerchantAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <link rel="icon" href="<?=GlobalUrlService::buildWwwStaticUrl("/images/favicon.ico");?>" type="image/x-icon"/>
    <title><?=Yii::$app->params["company"]["title"];?> -- 商户后台</title>
    <?php $this->head() ?>
    <?php $this->beginBody() ?>
</head>
<body>
<div class="page_wrap">
    <div class="box_wrap">
        <div class="box_left_nav">
            <h1 class="logo-default">
                <a target="_blank" href="<?= GlobalUrlService::buildWwwUrl("/"); ?>">
                    <img src="<?= GlobalUrlService::buildWwwStaticUrl("/images/logo_tiny.png"); ?>" alt="<?= Yii::$app->params['company']['title']; ?>" class="tiny"/>
                    <img src="<?= GlobalUrlService::buildWwwStaticUrl("/images/logo.png"); ?>" alt="<?= Yii::$app->params['company']['title']; ?>" class="normal"/>
                </a>
            </h1>

            <h2 class="version">云客服</h2>
            <ul class="menu_list">
                <li class="dashboard">
                    <a href="<?= GlobalUrlService::buildMerchantUrl("/"); ?>">
                        <i class="icon_club">&#xe6c0;</i><span>仪表盘</span>
                    </a>
                </li>
                <li class="chat">
                    <a href="<?= GlobalUrlService::buildMerchantUrl("/chat/log"); ?>">
                        <i class="icon_club">&#xe61e;</i><span>日志</span>
                    </a>
                </li>
                <li class="stat">
                    <a href="<?= GlobalUrlService::buildMerchantUrl("/stat/trace"); ?>">
                        <i class="fa fa-pie-chart fa-lg"></i><span>统计</span>
                    </a>
                </li>
                <li class="staff">
                    <a href="<?= GlobalUrlService::buildMerchantUrl("/staff/index"); ?>">
                        <i class="icon_club">&#xe60b;</i><span>客服</span>
                    </a>
                </li>
                <li class="help">
                    <a href="<?= GlobalUrlService::buildMerchantUrl("/help/index"); ?>">
                        <i class="icon_club">&#xe624;</i><span>接入帮助</span>
                    </a>
                </li>
                <li>
                    <a target="_blank" href="<?= GlobalUrlService::buildMerchantUrl("/help/cs"); ?>">
                        <i class="icon_club">&#xe60c;</i><span>客服工作台</span>
                    </a>
                </li>
            </ul>
            <span class="menu_switch"><i class="icon_club">&#xe602;</i><i class="icon_club arrow_left">&#xe60e;</i></span>
        </div>
        <div class="box_main">
            <div class="box_top">
                <div class="row">
                    <div class="row-in">
                        <div class="columns-24">
                            <div class="top_right hastips">
                                <a href="<?= GlobalUrlService::buildMerchantUrl("/notice/index") ?>" class="icon_club hide" data-tip="消息">
                                    <span class="icon_club icon1">&#xe60a;</span>
                                </a>

                                <a href="javascript:void(0);" class="icon_club user has-panel" data-panel="user_menu">
                                    <img src="<?= GlobalUrlService::buildWwwStaticUrl("/images/no-avatar.png"); ?>" alt="80*80"/>
                                </a>
                                <ul class="user_menu hide">
                                    <li class="user_profile border">
                                        <p class="icon_club user">
                                            <img src="<?= GlobalUrlService::buildWwwStaticUrl("/images/no-avatar.png"); ?>" alt="80*80"/>
                                        </p>
                                        <p class="t1">
                                            <label class="t2"><?= $this->params['current_user']["login_name"]; ?></label>
                                        </p>
                                        <p class="t3"><?= $this->params['current_user']["login_name"]; ?></p>
                                        <a href="<?= GlobalUrlService::buildMerchantUrl("/user/set"); ?>" class="user_edit hide" style="display: none;">编辑</a>
                                    </li>
                                    <li class="each border" style="display: none;">
                                        <a href="<?= GlobalUrlService::buildMerchantUrl("/user/pwd"); ?>"><i
  class="icon_club">&#xe610;</i>修改密码</a>
                                    </li>
                                    <li class="each">
                                        <a href="<?= GlobalUrlService::buildMerchantUrl("/user/logout"); ?>"><i class="icon_club">&#xe618;</i>退出</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content_wrap">
                <?php echo $content ?>
            </div>
        </div>
    </div>
    <div class="footer_wrap">
        <div class="inner">
            <?= Yii::$app->params['company']['copyright']; ?>
            &nbsp;&nbsp;|&nbsp;&nbsp;<?= Yii::$app->params['company']['phone']; ?>
        </div>
    </div>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>