www/controllers/CodeController.php
<?php
namespace www\controllers;

use common\components\DataHelper;
use common\components\GlobalUrlService;
use common\components\UtilHelper;
use common\models\merchant\Merchant;
use common\models\merchant\MerchantConfig;
use common\services\chat\ChatService;
use common\services\Constants;
use common\services\EventsDispatch;
use common\services\MerchantService;
use www\controllers\common\BaseController;

class CodeController extends BaseController {

	public function __construct($id, $module, $config = []){
		parent::__construct($id, $module, $config = []);
		$this->layout = false;
	}

    public function actionIndex(){
		header('Content-type: text/javascript');

		$iframe_url = GlobalUrlService::buildWwwUrl( "/code/chat" );

		$uuid = UtilHelper::gene_guid()."_".time();
        return $this->render("index.js",[
        	"iframe_url" => $iframe_url,
			"uuid" => md5($uuid),
            "is_pc" => UtilHelper::isPC()?"1":"0"
		]);
    }

    public function actionChat(){
		$ws_url = \Yii::$app->params['websocket'];
		$uuid = $this->get("uuid","");
		$data = json_encode( [
			"ws_url" => $ws_url,
			"uuid" => $uuid,
			"guest_avatar" => GlobalUrlService::buildWwwStaticUrl("/images/".Constants::$default_kf_avatar ),
            "kf_avatar" => GlobalUrlService::buildWwwStaticUrl("/images/".Constants::$default_kf_avatar )
		] );
		return $this->render("chat_mini",[
		    "params" => $data
        ]);
	}
}

www/controllers/ErrorController.php
<?php

namespace www\controllers;

use www\controllers\common\BaseController;
use Yii;
use yii\log\FileTarget;
use yii\web\Response;

class ErrorController extends BaseController
{
	public $enableCsrfValidation = false;

	public function actionError()
	{
		$error = Yii::$app->errorHandler->exception;

		if ($error) {
			$code = $error->getCode();
			$msg  = $error->getMessage();
			$file = $error->getFile();
			$line = $error->getLine();

			$time = microtime(true);
			$log  = new FileTarget();
			$log->logFile = Yii::$app->getRuntimePath() . '/logs/err.log';

			$err_msg = $msg . " [file: {$file}][line: {$line}][err code:$code.]" .
				"[url:{$_SERVER['REQUEST_URI']}][post:" . http_build_query($_POST) . "]";


			$log->messages[] = [
				$err_msg,
				1,
				'application',
				$time
			];
			$log->export();

		}


		$response = Yii::$app->response;
		$response->format = Response::FORMAT_JSON;
		$response->data   = [
			'msg'    => isset($msg) ? $msg : '',
			'code'   => isset($code) ? $code : -200,
			'data'   => [],
			'req_id' => uniqid()
		];

		return $response;
	}


}

www/controllers/IndexController.php
<?php
namespace www\controllers;

use www\controllers\common\BaseController;

class IndexController extends BaseController {

    public function actionIndex(){
        return $this->render('index');
    }
}

www/controllers/UserController.php
<?php
namespace www\controllers;

use common\components\GlobalUrlService;
use common\components\UtilHelper;
use common\models\merchant\Merchant;
use common\models\sms\SmsCaptcha;
use common\services\captcha\ValidateCode;
use common\services\MerchantService;
use www\controllers\common\BaseController;

class UserController extends BaseController {

	public function __construct($id, $module, array $config = []){
		parent::__construct($id, $module, $config);
		$this->layout = false;
	}

	public function actionLogin(){
	    if( \Yii::$app->request->isGet ){
	        if( $this->getCookie( $this->auth_merchant_cookie ) ){
	            return $this->redirect( GlobalUrlService::buildMerchantUrl("/") );
            }
            return $this->render('login');
        }
        $login_name = trim( $this->post("login_name","") );
        $login_pwd = trim( $this->post("login_pwd","") );

        if( mb_strlen($login_name,"utf-8") <= 0 ){
            return $this->renderErrorJSON([],"请输入正确的登录用户名~~");
        }

        $merchant_info = Merchant::find()->where([ 'login_name' => $login_name,'status' => 1 ])->one();
        if( !$merchant_info ){
            return $this->renderErrorJSON([],"请输入正确的用户名和密码-1~~");
        }

        if( !$merchant_info->verifyPassword($login_pwd)){
            return $this->renderErrorJSON([],"请输入正确的用户名和密码-2~~" );
        }

        $this->createMerchantLoginStatus( $merchant_info );

        return $this->renderJSON( [
            'url' => GlobalUrlService::buildWwwUrl("/merchant/default/index")
        ],"登录成功~~" );
    }

}

www/views/index/index.php
<?php
use \common\components\GlobalUrlService;
?>
<div class="jumbotron">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-8">
                <h1 class="display-3">优秀的客服系统</h1>
                <p>我们的客服系统使用世界上最好的语言PHP进行开发，架构是Yii2 + GatewayWorker + Mysql + Redis 支持高并发</p>
                <p>支持PC + 手机H5 + 微信小程序 + 微信公众号</p>
                <p>浪子开源云客服交流群：<a target="_blank" href="//shang.qq.com/wpa/qunwpa?idkey=fd865a667498c7256ae33d274ab97cfaa7f97ac7e23f061b9a37c4619ddef37e"><img border="0" src="//pub.idqqimg.com/wpa/images/group.png" alt="浪子开源云客服交流群" title="浪子开源云客服交流群"></a></p>
                <p><?=Yii::$app->params['auth_busi'];?></p>
            </div>
            <div class="col-lg-4">
                <div class="card">
                    <img class="card-img-top"  style="width: 100%; display: block;" src="<?=GlobalUrlService::buildWwwStaticUrl("/images/auth/merge.png");?>">
                </div>
            </div>
        </div>

    </div>
</div>
<div class="row" style="padding: 0 5rem;">
    <div class="col-lg-4">
        <h2>整合简单，快速部署</h2>
        <p>您只需要一段js便可以使您的网站拥有客服功能，为您的会员提供最优服务。</p>
    </div>
    <div class="col-lg-4">
        <h2>用世界上最好的语言编写</h2>
        <p>系统采用 Yii2 + GatewayWorker 编写，性能强悍，完全满足您的企业咨询需求。</p>
    </div>
    <div class="col-lg-4 d-none">
        <h2>提供源码，随心所欲</h2>
        <p>您不需为购买的客服坐席到期而烦恼，也无需为您的数据安全担心。自己搭建，控制权在自己。</p>
    </div>
    <div class="col-lg-4">
        <h2>Saas多商户客服系统</h2>
        <p>您不需为购买的客服坐席到期而烦恼，也无需为您的数据安全担心。</p>
    </div>
</div>
<div class="row" style="padding: 0 5rem;">
    <div class="col-lg-12">
        <hr/>
    </div>
    <div class="col-lg-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                开源版本
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title text-center text-success">¥ 0.00</h1>
                <ul>
                    <li>获取开源V1版全部的源码</li>
                    <li>技术架构：Yii2 + GatewayWorker + Mysql  </li>
                    <li>QQ群交流， 不提供技术支持</li>
                    <li>仅供学习参考使用，不可商用</li>
                    <li>功能包含：</li>
                    <li>1. 提供商家和客服后台</li>
                    <li>2. 游客聊天</li>
                    <li>3. 提供来路和浏览器统计</li>
                    <li>4. 商家后台添加客服</li>
                    <li>5. 支持PC + 手机端</li>
                    <li style="visibility: hidden;">&nbsp;</li>
                    <li style="visibility: hidden;">&nbsp;</li>
                    <li style="visibility: hidden;">&nbsp;</li>
                    <li style="visibility: hidden;">&nbsp;</li>
                    <li style="visibility: hidden;">&nbsp;</li>
                    <li style="visibility: hidden;">&nbsp;</li>
                </ul>
                <button type="button" data-toggle="modal" data-target="#pop_auth" class="btn btn-lg btn-block btn-outline-primary">获取开源V1版本</button>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                单商户收费版本
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title text-center text-success">¥ 1299.00</h1>
                <ul>
                    <li>获取单商户收费全部的源码</li>
                    <li>技术架构：Yii2 + GatewayWorker + Mysql  </li>
                    <li>专门商业服务群，提供技术支持</li>
                    <li>授权可商用</li>
                    <li>功能包含：</li>
                    <li>1. 提供商家和客服后台</li>
                    <li>2. 游客聊天</li>
                    <li>3. 提供来路、浏览器、操作系统、设备、访问量统计</li>
                    <li>4. 留言功能</li>
                    <li>5. 商家后台添加客服</li>
                    <li>6. 支持PC + 手机端 + 微信小程序</li>
                    <li style="visibility: hidden;">&nbsp;</li>
                    <li style="visibility: hidden;">&nbsp;</li>
                    <li style="visibility: hidden;">&nbsp;</li>
                    <li style="visibility: hidden;">&nbsp;</li>
                </ul>
                <button type="button"  data-toggle="modal" data-target="#pop_auth" class="btn btn-lg btn-block btn-outline-primary">获取授权</button>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                多商户高并发收费版本
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title text-center text-success">¥ 3499.00</h1>
                <ul>
                    <li>获取多商户高并发收费全部的源码</li>
                    <li>技术架构：Yii2 + GatewayWorker + Mysql + Redis </li>
                    <li>专门商业服务群，提供技术支持</li>
                    <li>授权可商用、会持续更新</li>
                    <li>功能包含：</li>
                    <li>1. 提供商家和客服后台</li>
                    <li>2. 游客聊天，支持游客编号</li>
                    <li>3. 提供来路、浏览器、操作系统、设备、访问量统计</li>
                    <li>4. 留言功能</li>
                    <li>5. 商家后台添加客服</li>
                    <li>6. 定制化设置商户配置（自动弹出、浮层名称、商户名称）</li>
                    <li>7. 支持PC + 手机端 + 微信小程序 + 微信公众号</li>
                </ul>
                <button type="button"  data-toggle="modal" data-target="#pop_auth" class="btn btn-lg btn-block btn-outline-primary">获取授权</button>
            </div>
        </div>
    </div>
    <div class="col-lg-12">
        <hr/>
    </div>
    <div class="col-lg-12">
        <img src="<?=GlobalUrlService::buildWwwStaticUrl("/images/example/screen_3.png");?>" class="img-fluid">
        <img src="<?=GlobalUrlService::buildWwwStaticUrl("/images/example/screen_1.png");?>" class="img-fluid">
        <img src="<?=GlobalUrlService::buildWwwStaticUrl("/images/example/screen_2.jpg");?>" class="img-fluid">
    </div>
</div>

<div class="modal fade" id="pop_auth" tabindex="-1" role="dialog"  aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">联系方式
                    <a class="btn btn-success mb-3 mb-md-0 ml-md-3" target="_blank" href="<?=Yii::$app->params['auth_domain'];?>">授权官方网站</a></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="card-group">
                    <div class="card">
                        <img class="card-img-top" src="<?=GlobalUrlService::buildWwwStaticUrl("/images/auth/qq.png");?>">
                        <div class="card-body">
                            <h5 class="card-title">QQ群</h5>
                            <p class="card-text">加入QQ群咨询群主</p>
                        </div>
                    </div>
                    <div class="card">
                        <img class="card-img-top" src="<?=GlobalUrlService::buildWwwStaticUrl("/images/auth/wechat_fwh.png");?>">
                        <div class="card-body">
                            <h5 class="card-title">微信公众号</h5>
                            <p class="card-text">关注公众号获得即时更新通知</p>
                        </div>
                    </div>
                    <div class="card">
                        <img class="card-img-top" src="<?=GlobalUrlService::buildWwwStaticUrl("/images/auth/wechat_my.png");?>">
                        <div class="card-body">
                            <h5 class="card-title">个人微信</h5>
                            <p class="card-text">加个人微信咨询商业版本</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <?=Yii::$app->params['auth_busi'];?>
            </div>
        </div>
    </div>
</div>
<script>
    <!--ST客服代码-->
    (function () {
        var _stkf_code = document.createElement("script");
        _stkf_code.src = "//v1.stkf.test/code/index";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(_stkf_code, s);
    })();
</script>

www/views/layouts/js.php
<script type='text/javascript'>
    alert('<?=$msg;?>');
    window.location.href = '<?=$location;?>';
</script>

www/views/layouts/main.php
<?php

use yii\helpers\Html;
use www\assets\AppAsset;
use \common\components\GlobalUrlService;
AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge;chrome=1" />
    <title><?=Yii::$app->params["company"]["title"];?> -- 让交流更简单</title>
    <link rel="icon" href="<?=GlobalUrlService::buildWwwStaticUrl("/images/favicon.ico");?>" type="image/x-icon"/>
    <meta name="description" content="">
	<?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="javascript:void(0);" style="height: 40px;padding: 0;">
        <img class="rounded-circle" src="<?=GlobalUrlService::buildWwwStaticUrl("/images/logo.png");?>" title="<?=Yii::$app->params["company"]["title"];?>" style="height: 40px;" />
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="javascript:void(0);">首页</a>
            </li>
        </ul>
        <a class="btn btn-primary" href="<?=GlobalUrlService::buildWwwUrl("/user/login");?>">登录</a>
        <a class="btn btn-success mb-3 mb-md-0 ml-md-3" target="_blank" href="<?=Yii::$app->params['auth_domain'];?>">授权官方网站</a>
    </div>
</nav>
<div class="container-fluid" style="margin-top: 56px;min-height: 600px; padding: 0;" >
    <?= $content ?>
</div>

<footer class="text-muted" style="color: #6c757d!important;">
    <hr>
    <div class="container">
        <p><?=Yii::$app->params['company']['copyright'];?></p>
    </div>
</footer>
<script src="<?=GlobalUrlService::buildWwwUrl("/static/plugins/jquery/jquery.min.js" );?>"></script>
<!--IE8只能支持jQuery1.9-->
<!--[if lte IE 8]>
<script src="<?= GlobalUrlService::buildWwwStaticUrl("/plugins/jquery/jquery_1_9.min.js"); ?>"></script>
<![endif]-->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>